stages:
    - build


build_gcc_ninja:
    stage: build
    script:
        - ./compile.sh -g ninja
    artifacts:
        paths:
            - ./src/build
            - ./bin
            - ./lib/cfitsio
            - ./lib/CCfits
        expire_in: 1 week

build_gcc_make:
    stage: build
    script:
        - ./compile.sh -g make
    artifacts:
        paths:
            - ./src/build
            - ./bin
            - ./lib/cfitsio
            - ./lib/CCfits
        expire_in: 1 week

build_icc_ninja:
    stage: build
    script:
        - module load intel/icc/19.0.0
        - ./compile.sh -t -c icc -g ninja
        - module unload intel/icc/19.0.0
    artifacts:
        paths:
            - ./src/build
            - ./bin
            - ./lib/cfitsio
            - ./lib/CCfits
        expire_in: 1 week

build_clang_ninja:
    stage: build
    script:
        - ./compile.sh -c clang++ -g ninja
    artifacts:
        paths:
            - ./src/build
            - ./bin
            - ./lib/cfitsio
            - ./lib/CCfits
        expire_in: 1 week
